### ISSUE TITLE
How to unify the MS-COCO keypoint numbers with the MPII

### ISSUE THREAD

**Issue by ysq319** [Xxxia96/Pose_DomainAdaption#1]
your work surprised me. And I would appreciate it if you can give out some detail about the keypoint unification of the two datasets since the keypoints of the two datasets are not one-to-one corresponding.
By the way, expect your code available.

**Comment by anibali** [comment]
I have the same question. For example, Figure 3 in the paper clearly shows eye keypoints in the last row (labelled as "mpii"), when the MPII dataset does not include eye keypoint annotations. Does this method allow for adaptation across different sets of keypoints, or is something else going on here?

**Comment by Xxxia96** [comment]
Thanks for you questions. And this method doesn't allow for adaptation across different sets of keypoints actually. And we feel sorry about that we don't explain clearly in the paper. Actually, we preprocess the MPII and relabelled the related keypoints, make it keep consistent with the COCO. 


	-----原始邮件-----
发件人:"Aiden Nibali" <notifications@github.com>
发送时间:2021-01-27 06:55:09 (星期三)
收件人: Sophie-Xu/Pose_DomainAdaption <Pose_DomainAdaption@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [Sophie-Xu/Pose_DomainAdaption] How to unify the MS-COCO keypoint numbers with the MPII (#1)

	
		
	
	
		I have the same question. For example, Figure 3 in the paper clearly shows eye keypoints in the last row (labelled as "mpii"), when the MPII dataset does not include eye keypoint annotations. Does this method allow for adaptation across different sets of keypoints, or is something else going on here?
