### ISSUE TITLE
Different keypoints for source and target dataset

### ISSUE THREAD

**Issue by SuperJay1996** [Xxxia96/Pose_DomainAdaption#3]
Hello,
Thanks for your interesting research.
I notice that "We unify the MS-COCO keypoint numbers with the MPII finally" in the published article. However, there are 12 same keypoints for both datasets. I wonder that which means do you use for unify?

**Comment by Sophie-Xu** [comment]
Yeah, actually we change the COCO annotations for some joints and make new labeled infos for the different types of joints with MPII and ignore another one.

**Comment by Xxxia96** [comment]
> Hello,
> Thanks for your interesting research.
> I notice that "We unify the MS-COCO keypoint numbers with the MPII finally" in the published article. However, there are 12 same keypoints for both datasets. I wonder that which means do you use for unify?

Thanks for you questions.  Actually, we preprocess the MPII and relabelled the related keypoints, make it keep consistent with the COCO.
