### ISSUE TITLE
Confusion regarding lSA, IHTA

### ISSUE THREAD

**Issue by driptaRC** [Xxxia96/Pose_DomainAdaption#4]
In both Intra-domain Structure Adaptation (ISA) and Inter-domain Human-Topology Alignment (IHTA), the loss terms contain cosine similarities. Why are you minimizing them? Shouldn't it be maximizing similarities?

**Comment by Xxxia96** [comment]
Thanks for your attention. Yes, you are right and we also maxmize their similarity indeed. I'm sorry about that actually a minus sign is missing in our loss description. A '-' sign should occur in front of the loss formula and we minimize that.发自我的华为手机-------- 原始邮件 --------发件人： "Dripta S. Raychaudhuri" ***@***.***>日期： 2022年1月14日周五 21:12收件人： Sophie-Xu/Pose_DomainAdaption ***@***.***>抄送： Subscribed ***@***.***>主    题： [Sophie-Xu/Pose_DomainAdaption] Confusion regarding lSA, IHTA (Issue #4)
In both Intra-domain Structure Adaptation (ISA) and Inter-domain Human-Topology Alignment (IHTA), the loss terms contain cosine similarities. Why are you minimizing them? Shouldn't it be maximizing similarities?
